# Generated by Django 4.1.7 on 2023-03-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
