# Generated by Django 4.1.7 on 2023-03-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_product_images',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
