# Generated by Django 4.1.7 on 2023-03-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_vendor_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_product_images',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
