# Generated by Django 4.1.7 on 2023-03-31 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_alter_vendor_product_images_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_product_images',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor_product_images',
            name='vendor_product',
        ),
        migrations.RemoveField(
            model_name='cart_detail',
            name='vendorProduct',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='vendor_product',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vendor_product',
        ),
        migrations.DeleteModel(
            name='Vendor_product_images',
        ),
    ]
