# Generated by Django 4.1.7 on 2023-03-31 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_vendor_product_images_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
